
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include "log.h"
#include "executor.h"
#include "hop.h"
#include "reveal.h"
#include "proclore.h"
#include "seek.h"
#include "utils.h"
#include "redirection.h"
#include "piping.h"

#include "fg_bg.h"
#include "neonate.h"
#include "mysh.h"
#include "input.h"
#include "signals.h"
#include "iman.h"
#include <errno.h>
#include "prompt.h"
#include "iman.h"
#include <string.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netdb.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/time.h>
#include <errno.h>
#include "executor.h"
#include "activity.h"
#include "input.h"
#include "signals.h"

#include <stdlib.h>
#include <dirent.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/select.h>
#include <ctype.h>
#include <arpa/inet.h>
#include <netdb.h>